/* HairSoft V125 – warehouse tables, search and management. */
(function(){'use strict';
  if(!/[?&]strana=Sklad(?:Xml)?(?:&|$)/i.test(location.search) && !document.querySelector('#sklad1,#sklad2'))return;
  function tr(s){return window.hsTranslate?window.hsTranslate(s):s;}
  function label(n,s){if(window.hsSetTranslatedText)window.hsSetTranslatedText(n,s);else n.textContent=s;}
  function icon(name){var paths={box:'M3 7l9-4 9 4v10l-9 4-9-4V7Zm0 0 9 4 9-4M12 11v10',search:'M21 21l-5-5',export:'M12 3v12M7 10l5 5 5-5M5 20h14',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',refresh:'M20 11a8 8 0 1 0-2.34 5.66M20 4v7h-7',trash:'M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5'};return '<svg viewBox="0 0 24 24" aria-hidden="true">'+(name==='search'?'<circle cx="10" cy="10" r="7"></circle>':'')+'<path d="'+paths[name]+'"></path></svg>';}
  function heading(panel,title,type){if(panel.dataset.hsStockHeading)return;panel.dataset.hsStockHeading='1';var head=panel.querySelector('.panel-heading');if(!head){head=document.createElement('div');head.className='panel-heading';panel.insertBefore(head,panel.firstChild);}head.innerHTML='<span class="hs-stock-heading-icon">'+icon(type||'box')+'</span><h3 class="panel-title"></h3>';label(head.querySelector('h3'),title);}
  function negative(value){return /^[-−]/.test(String(value).trim()) && Number(String(value).replace(/\s/g,"").replace("−","-").replace(",",".")) < 0;}
  function cards(table,api){var wrap=table.closest('.dataTables_wrapper'),host=wrap.querySelector('.hs-stock-cards');if(!host){host=document.createElement('div');host.className='hs-stock-cards';wrap.insertBefore(host,table);}host.textContent='';var headers=Array.from(table.tHead.rows[0].cells).map(c=>c.textContent.trim());api.rows({search:'applied',order:'applied',page:'current'}).every(function(){Array.from(this.node().cells).forEach(function(c,i){c.classList.toggle("hs-stock-negative",i>=3&&negative(c.textContent));});var cells=Array.from(this.node().cells).map(c=>c.textContent.trim());if(cells.length!==headers.length)return;var article=document.createElement('article');article.className='hs-stock-product';var head=document.createElement('header'),name=document.createElement('strong'),plu=document.createElement('span');name.textContent=cells[2];plu.textContent='PLU · '+cells[1];head.appendChild(plu);head.appendChild(name);article.appendChild(head);var grid=document.createElement('div');grid.className='hs-stock-product-values';for(var i=3;i<cells.length;i++){var row=document.createElement('div'),title=document.createElement('span'),value=document.createElement('strong');label(title,headers[i]);value.textContent=cells[i];if(negative(cells[i]))value.classList.add("hs-stock-negative");row.appendChild(title);row.appendChild(value);grid.appendChild(row);}article.appendChild(grid);host.appendChild(article);});if(!host.children.length){var empty=document.createElement('p');label(empty,'Nic nenalezeno');host.appendChild(empty);}}
  function enhance(table){if(!window.jQuery||!jQuery.fn.dataTable.isDataTable(table))return;var api=jQuery(table).DataTable(),wrap=table.closest('.dataTables_wrapper');if(!wrap)return;
    if(!table.dataset.hsStock){table.dataset.hsStock='1';var panel=table.closest('.panel');panel.classList.add('hs-stock-panel','hs-stock-table-panel');heading(panel,table.id==='sklad1'?'Aktuální stav zásob':'Seznam chybějícího zboží');var toolbar=document.createElement('div');toolbar.className='hs-stock-toolbar';wrap.insertBefore(toolbar,wrap.firstChild);var filter=wrap.querySelector('.dataTables_filter'),buttons=wrap.querySelector('.dt-buttons');if(filter){toolbar.appendChild(filter);var l=filter.querySelector('label'),input=filter.querySelector('input');Array.from(l.childNodes).filter(n=>n.nodeType===3).forEach(n=>n.remove());var ico=document.createElement('span');ico.innerHTML=icon('search');l.insertBefore(ico,input);if(window.hsSetTranslatedAttribute){hsSetTranslatedAttribute(input,'placeholder','Hledat podle názvu nebo PLU…');hsSetTranslatedAttribute(input,'aria-label','Hledat podle názvu nebo PLU…');}else{input.placeholder=tr('Hledat podle názvu nebo PLU…');input.setAttribute('aria-label',tr('Hledat podle názvu nebo PLU…'));}}if(buttons){toolbar.appendChild(buttons);var button=buttons.querySelector('.buttons-collection');button.innerHTML=icon('export')+'<span></span>';label(button.querySelector('span'),'Export');}
      jQuery(table).on('draw.dt.hsStock',function(){cards(table,api);});
    }cards(table,api);
  }
  function decorateAction(button,type,title){if(!button||button.dataset.hsStock)return;button.dataset.hsStock='1';button.textContent='';button.insertAdjacentHTML('beforeend',icon(type));var span=document.createElement('span');if(title)label(span,title);else span.textContent=button.getAttribute('data-hs-label')||'';button.appendChild(span);}
  function prepareManagement(main){var details=main.querySelector('.hs-stock-data-management');if(!details)return;var iconHost=details.querySelector('.hs-stock-data-management-icon'),title=details.querySelector('.hs-stock-data-management-label');if(iconHost&&!iconHost.firstChild)iconHost.innerHTML=icon('settings');if(title)label(title,'Správa dat');
    details.querySelectorAll('[name="SmazatSkladForm"],[name="DeleteSkladData"]').forEach(function(input){var button=input.form?input.form.querySelector('button'):null;decorateAction(button,'trash',input.name==="DeleteSkladData"?'Smazat kompletní stav skladu':'Smazat informace o skladu');});
    details.querySelectorAll('[name="RefreshSkladuZPC"]').forEach(function(input){var button=input.form?input.form.querySelector('button'):null;if(!button||button.dataset.hsStock)return;var text=button.textContent.trim();button.dataset.hsStock='1';button.textContent='';button.insertAdjacentHTML('beforeend',icon('refresh'));var span=document.createElement('span');span.textContent=text;button.appendChild(span);});
  }
  function prepare(){var main=document.getElementById('main-content');if(!main)return;main.classList.add('hs-stock-page');main.querySelectorAll('#sklad1,#sklad2').forEach(enhance);var picker=main.querySelector('#idSkladuForm');if(picker){var p=picker.closest('.panel');p.classList.add('hs-stock-panel','hs-stock-picker');heading(p,'Výběr skladu');}
    prepareManagement(main);
    main.querySelectorAll('[name="SmazatSkladForm"],[name="DeleteSkladData"]').forEach(function(input){if(input.closest('.hs-stock-data-management'))return;var p=input.closest('.panel');if(!p)return;p.classList.add('hs-stock-panel','hs-stock-options');heading(p,'Správa dat','settings');var button=input.form.querySelector('button');if(button&&!button.dataset.hsStock){button.dataset.hsStock='1';var title=input.name==="DeleteSkladData"?"Smazat kompletní stav skladu":"Smazat informace o skladu";button.textContent='';button.insertAdjacentHTML('beforeend',icon('trash'));var span=document.createElement('span');label(span,title);button.appendChild(span);}});
    main.classList.add('hs-stock-ready');
  }
  function boot(){prepare();if(window.jQuery)jQuery(document).on('init.dt.hsStock',function(e,settings){if(settings.nTable.id==='sklad1'||settings.nTable.id==='sklad2')prepare();});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
  document.addEventListener('hs:languagechange',function(){var main=document.querySelector('.hs-stock-page');if(!main)return;main.querySelectorAll('.dataTables_filter input').forEach(n=>{n.placeholder=tr('Hledat podle názvu nebo PLU…');n.setAttribute('aria-label',tr('Hledat podle názvu nebo PLU…'));});});
}());
