/* V127 – presentation only. Original form nodes, fields and submit handlers stay intact. */
(function(){'use strict';
 var main=document.querySelector('.hs-voucher-page');if(!main)return;
 var page=main.dataset.voucherPage;
 function tr(s){return window.hsTranslate?window.hsTranslate(s):s;}
 function label(n,s){if(window.hsSetTranslatedText)window.hsSetTranslatedText(n,s);else n.textContent=s;}
 function icon(name){var paths={voucher:'M3 5h18v5a2 2 0 0 0 0 4v5H3v-5a2 2 0 0 0 0-4V5Zm12 0v3m0 3v2m0 3v3',search:'M21 21l-5-5',export:'M12 3v12M7 10l5 5 5-5M5 20h14',edit:'m15 4 5 5M4 20l5-1L21 7l-5-5L4 14v6',back:'m14 5-7 7 7 7',trash:'M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5',filter:'M4 7h16M4 17h16M8 4v6M16 14v6'};return '<svg viewBox="0 0 24 24" aria-hidden="true">'+(name==='search'?'<circle cx="10" cy="10" r="7"></circle>':'')+'<path d="'+paths[name||'voucher']+'"></path></svg>';}
 var headers={};
 function canonicalStatus(s){var sets=[['V oběhu','V obehu','In circulation','Im Umlauf'],['Neplatný','Invalid','Ungültig'],['Vyčerpaný','Fully redeemed','Vollständig eingelöst'],['Částečně čerpaný','Čiastočne čerpaný','Partially redeemed','Teilweise eingelöst']];s=s.replace(/\s+/g,' ').trim();var match=sets.find(function(a){return a.indexOf(s)>=0;});return match?match[0]:s;}
 // Read canonical sources from the server-authored header attributes before any translation.
 main.querySelectorAll('table[id]').forEach(function(t){if(t.tHead)headers[t.id]=Array.from(t.tHead.rows[0].cells).map(function(c){return c.getAttribute('data-hs-voucher-header')||c.textContent.trim();});});
 function cards(table,api){var wrap=table.closest('.dataTables_wrapper'),host=wrap.querySelector('.hs-voucher-cards');if(!host){host=document.createElement('div');host.className='hs-voucher-cards';wrap.insertBefore(host,wrap.querySelector('.hs-voucher-scroll')||table);}host.textContent='';var names=headers[table.id];
  api.rows({search:'applied',order:'applied',page:'current'}).every(function(){var nodes=Array.from(this.node().cells);if(nodes.length!==names.length)return;var vals=nodes.map(function(n){return n.textContent.trim();}),article=document.createElement('article');article.className='hs-voucher-product';var head=document.createElement('header'),strong=document.createElement('strong'),code=names.indexOf('Kód');strong.textContent=code>=0?vals[code]:tr('Sumář');head.appendChild(strong);
   var original=nodes[0].querySelector('a[href]');if(original){var a=original.cloneNode(false);a.className='hs-voucher-detail';label(a,'Detail');head.appendChild(a);}article.appendChild(head);var grid=document.createElement('div');grid.className='hs-voucher-product-values';nodes.forEach(function(n,i){if(i===code||(i===0&&original))return;var row=document.createElement('div'),title=document.createElement('span'),value=document.createElement('strong');label(title,names[i]);if(names[i]==='Stav')label(value,canonicalStatus(vals[i]));else value.textContent=vals[i];if(names[i]==='Zůstatek')row.classList.add('hs-voucher-balance');if(/^[-−]\s*\d/.test(vals[i]))value.classList.add('hs-voucher-negative');row.appendChild(title);row.appendChild(value);grid.appendChild(row);});article.appendChild(grid);host.appendChild(article);
  });if(!host.children.length){var p=document.createElement('p');label(p,'Nic nenalezeno');host.appendChild(p);}
 }
 function enhance(table){if(!window.jQuery||!jQuery.fn.dataTable.isDataTable(table)||table.dataset.hsVoucher)return;table.dataset.hsVoucher='1';var api=jQuery(table).DataTable(),wrap=table.closest('.dataTables_wrapper'),panel=table.closest('.panel');panel.classList.add('hs-voucher-table-panel');
  var toolbar=document.createElement('div');toolbar.className='hs-voucher-toolbar';wrap.insertBefore(toolbar,wrap.firstChild);var filter=wrap.querySelector('.dataTables_filter'),buttons=wrap.querySelector('.dt-buttons');
  if(filter){toolbar.appendChild(filter);var l=filter.querySelector('label'),input=filter.querySelector('input');Array.from(l.childNodes).filter(function(n){return n.nodeType===3;}).forEach(function(n){n.remove();});var ico=document.createElement('span');ico.innerHTML=icon('search');l.insertBefore(ico,input);['placeholder','aria-label'].forEach(function(attr){if(window.hsSetTranslatedAttribute)hsSetTranslatedAttribute(input,attr,'Hledat voucher…');else input.setAttribute(attr,tr('Hledat voucher…'));});}
  if(buttons){toolbar.appendChild(buttons);var button=buttons.querySelector('.buttons-collection');if(button){button.innerHTML=icon('export')+'<span></span>';label(button.querySelector('span'),'Export');}}
  var copy=api.button('0-0').node();if(copy&&copy[0])label(copy[0],'Kopírovat');
  if(headers[table.id].length>6){var scroll=document.createElement('div');scroll.className='hs-voucher-scroll';table.parentNode.insertBefore(scroll,table);scroll.appendChild(table);
   var top=document.createElement('div'),track=document.createElement('div');top.className='hs-voucher-scroll-top';top.tabIndex=0;top.setAttribute('role','region');if(window.hsSetTranslatedAttribute)hsSetTranslatedAttribute(top,'aria-label','Posun tabulky');top.appendChild(track);scroll.parentNode.insertBefore(top,scroll);
   top.addEventListener('scroll',function(){if(scroll.scrollLeft!==top.scrollLeft)scroll.scrollLeft=top.scrollLeft;});scroll.addEventListener('scroll',function(){if(top.scrollLeft!==scroll.scrollLeft)top.scrollLeft=scroll.scrollLeft;});
   function sizeScroll(){track.style.width=scroll.scrollWidth+'px';top.classList.toggle('hs-voucher-scroll-unneeded',scroll.scrollWidth<=scroll.clientWidth+1);top.scrollLeft=scroll.scrollLeft;}
   if(window.ResizeObserver){var observer=new ResizeObserver(sizeScroll);observer.observe(table);observer.observe(scroll);}window.addEventListener('resize',sizeScroll);jQuery(table).on('draw.dt.hsVoucherScroll',sizeScroll);requestAnimationFrame(sizeScroll);
  }
  api.rows().every(function(){var cells=this.node().cells;Array.from(cells).forEach(function(c,i){if(headers[table.id][i]==='Stav'){var state=canonicalStatus(c.textContent),badge=document.createElement('span');badge.className='hs-voucher-status';badge.dataset.state=state;label(badge,state);c.textContent='';c.appendChild(badge);}if(i===0&&table.id==='TabulkaVouchery'){var a=c.querySelector('a[href]');if(a){a.className='hs-voucher-detail';label(a,'Detail');}}});});
  cards(table,api);jQuery(table).on('draw.dt.hsVoucher',function(){cards(table,api);});
 }
 function prepare(){main.querySelectorAll('.panel').forEach(function(p){var h=p.querySelector('.panel-heading [data-hs-voucher-label]');if(!h)return;p.classList.add('hs-voucher-panel');var head=h.closest('.panel-heading');if(!head.querySelector('.hs-voucher-heading-icon')){head.querySelectorAll('.actions').forEach(function(n){n.remove();});var ico=document.createElement('span');ico.className='hs-voucher-heading-icon';ico.innerHTML=icon('voucher');head.insertBefore(ico,head.firstChild);label(h,h.dataset.hsVoucherLabel);}
  if(h.dataset.hsVoucherLabel.indexOf('Editace')===0)p.classList.add('hs-voucher-edit');
 });
 main.querySelectorAll('button[data-hs-voucher-label]').forEach(function(b){if(b.dataset.hsVoucher)return;b.dataset.hsVoucher='1';var source=b.dataset.hsVoucherLabel;if(source==='×')return;var type=/^Smazat/.test(source)?'trash':/^Zpět/.test(source)?'back':/Export/i.test(source)?'export':/filtr/i.test(source)?'filter':/Editace|Uložit/.test(source)?'edit':'voucher';b.innerHTML=icon(type)+'<span></span>';label(b.querySelector('span'),source);});
 var filter=main.querySelector('#VoucherOdDo');if(filter)filter.closest('.panel').classList.add('hs-voucher-filter');
 if(page==='VoucherHistorie'){
  var deleteInput=main.querySelector('[name="SmazatCeninu"]');if(deleteInput&&!main.querySelector('.hs-voucher-delete-section')){var section=document.createElement('section');section.className='panel panel-default hs-voucher-panel hs-voucher-delete-section';section.innerHTML='<div class="panel-heading"><span class="hs-voucher-heading-icon">'+icon('trash')+'</span><h3 class="panel-title"></h3></div><div class="panel-body hs-voucher-actions"></div>';label(section.querySelector('h3'),'Správa dat');section.querySelector('.panel-body').appendChild(deleteInput.form);var footer=main.querySelector('.hs-page-status')||Array.from(main.querySelectorAll('font')).find(function(n){return /Strana načtena za|Page loaded in|Seite geladen in|Stránka načítaná za/.test(n.textContent);});if(footer){while(footer.parentElement!==main)footer=footer.parentElement;}if(footer)main.insertBefore(section,footer);else main.appendChild(section);}
  [['ZmenitHodnotuCeniny','hs-voucher-edit-amount'],['ZmenitPlatnost','hs-voucher-edit-validity']].forEach(function(pair){var input=main.querySelector('[name="'+pair[0]+'"]'),button=input&&input.form.querySelector('button');if(button)button.classList.add(pair[1]);});
  var history=main.querySelector('#example'),historyBody=history&&history.closest('.panel').querySelector('.panel-body');if(historyBody&&!historyBody.querySelector('.hs-voucher-detail-actions')){var actions=document.createElement('div');actions.className='hs-voucher-detail-actions';historyBody.querySelectorAll('form').forEach(function(f){actions.appendChild(f);});historyBody.querySelectorAll('.rada').forEach(function(n){if(!n.textContent.trim()&&!n.querySelector('form,input,button'))n.remove();});historyBody.querySelectorAll(':scope > br').forEach(function(n){n.remove();});historyBody.appendChild(actions);}
 }
 var manage=main.querySelector('[name="SmazatVsechnyVouchery"]');if(manage){var panel=manage.closest('.panel');if(panel&&!panel.querySelector('.panel-heading')){panel.classList.add('hs-voucher-panel');var head=document.createElement('div');head.className='panel-heading';head.innerHTML='<span class="hs-voucher-heading-icon">'+icon('filter')+'</span><h3 class="panel-title"></h3>';label(head.querySelector('h3'),'Správa dat');panel.insertBefore(head,panel.firstChild);}}
 // These action groups contain only original forms. Keep their owners and hidden inputs.
 main.querySelectorAll('form').forEach(function(f){if(f.id==='VoucherOdDo'||f.querySelector('input:not([type="hidden"]),select'))return;var parent=f.parentElement;if(parent&&parent.querySelectorAll(':scope > form').length>0)parent.classList.add('hs-voucher-actions');});
 main.querySelectorAll('#TabulkaVouchery,#example,#example2,#VoucherSumar,#VoucherSumarDeposit').forEach(enhance);
 }
 window.hsPrepareVoucherChart=function(){if(page!=='Voucher'||!window.config2)return;var panel=Array.from(main.querySelectorAll('.panel')).find(function(p){var h=p.querySelector('[data-hs-voucher-label="Graf čerpání"]');return !!h;});if(!panel||panel.dataset.hsChart)return;panel.dataset.hsChart='1';var legend=panel.querySelector('table'),body=panel.querySelector('.panel-body'),canvas=panel.querySelector('#chart-area1');if(!body||!legend)return;
  if(window.myDoughnut&&window.myDoughnut.destroy)window.myDoughnut.destroy();var layout=document.createElement('div');layout.className='hs-voucher-chart-layout';legend.className='hs-voucher-chart-legend';layout.appendChild(legend);var plot=document.createElement('div');plot.className='hs-voucher-chart-plot';layout.appendChild(plot);body.textContent='';body.appendChild(layout);
  var data=config2.data.datasets[0].data.map(function(v){return Number(v)||0;}),total=data.reduce(function(a,b){return a+b;},0),palette=['#14a5a0','#e6a132','#546d94'];Array.from(legend.rows).filter(function(r){return r.cells.length===3;}).forEach(function(r,i){var dot=r.cells[0].querySelector('div');if(dot)dot.style.backgroundColor=palette[2-i];});
  var currency=Array.from(main.querySelectorAll('.widget-mini .total')).map(function(n){return n.textContent.replace(/[0-9\s.,−-]/g,'').trim();}).find(function(s){return s;})||'';
  var center=document.createElement('div');center.className='hs-voucher-chart-total';center.textContent=total.toLocaleString('cs-CZ',{maximumFractionDigits:2})+(currency?' '+currency:'');var small=document.createElement('small');label(small,'Celkem');center.appendChild(small);
  if(total===0){var ring=document.createElement('div');ring.className='hs-voucher-empty-ring';plot.appendChild(ring);}else{if(!canvas){canvas=document.createElement('canvas');canvas.id='chart-area1';}plot.appendChild(canvas);var baseLabels=['Nečerpáno','Částečně','Vyčerpáno'];window.myDoughnut=new Chart(canvas.getContext('2d'),{type:'doughnut',data:{labels:baseLabels.map(tr),datasets:[{data:data,backgroundColor:palette,borderColor:'#fff',borderWidth:3}]},options:{responsive:true,maintainAspectRatio:false,cutoutPercentage:72,legend:{display:false},animation:{duration:0},tooltips:{enabled:true,callbacks:{label:function(item,d){return d.labels[item.index]+': '+Number(d.datasets[0].data[item.index]).toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2})+(currency?' '+currency:'');}}}}});document.addEventListener('hs:languagechange',function(){myDoughnut.data.labels=baseLabels.map(tr);myDoughnut.update();});}plot.appendChild(center);
  if(canvas&&window.myDoughnut){var touchEnd=0;canvas.addEventListener('touchend',function(){touchEnd=Date.now();},{passive:true});canvas.addEventListener('mouseout',function(e){if(Date.now()-touchEnd<700)e.stopImmediatePropagation();},true);document.addEventListener('touchstart',function(e){if(!plot.contains(e.target)&&window.myDoughnut)window.myDoughnut.eventHandler({type:'mouseout'});},{passive:true});}
 };
 prepare();if(window.jQuery)jQuery(document).on('init.dt.hsVoucher',function(){prepare();});
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',prepare);
 function finish(){prepare();window.hsPrepareVoucherChart();requestAnimationFrame(function(){requestAnimationFrame(function(){main.classList.add('hs-voucher-ready');var shell=main.closest('.hs-voucher-shell');if(shell)shell.classList.add('hs-voucher-shell-ready');document.querySelectorAll('.hs-voucher-load-error').forEach(function(n){n.remove();});});});}
 if(document.readyState==='complete')finish();else window.addEventListener('load',finish);
}());
